# Generated by Django 5.2 on 2025-05-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_country_candidate_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
