# Generated by Django 5.2 on 2025-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
